quarkus.langchain4j.easy-rag.path=easy-rag-catalog
quarkus.langchain4j.easy-rag.reuse-embeddings.enabled=true
quarkus.langchain4j.timeout=60s

# Quarkus Application Engine Controls
quarkus.log.level=INFO
quarkus.banner.enabled=false

# LangChain4j Local Ollama Endpoint Bindings
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=qwen3.5
quarkus.langchain4j.ollama.chat-model.temperature=0.0
quarkus.langchain4j.ollama.timeout=120s

